name: .NET Core (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci-mswin:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: MSVC CI
      working-directory: cs
      run: dotnet build

    - name: Install dependencies
      working-directory: cs
      run: dotnet restore GS1HealthcareGMN.sln
    - name: Build
      working-directory: cs
      run: dotnet build HealthcareGMN/HealthcareGMN.csproj --configuration Release --no-restore
    - name: Test
      working-directory: cs
      run: dotnet test HealthcareGMNTests/HealthcareGMNTests.csproj --no-restore --verbosity normal
